function plot_lane_flow(Y1, lane_id)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 13-Oct-2015 20:17:34

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',{'0','4','8','12','16','20','24'},...
    'XTick',[0 48 96 144 192 240 288],...
    'FontSize',16);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 300]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 250]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create plot
plot(Y1,'MarkerFaceColor',[1 0 0],'Marker','o','Color',[1 0 0]);

% Create xlabel
xlabel('Time [hour]');

% Create ylabel
ylabel('Vehicles per 5 min','FontSize',16);

ylim([0, 250]);

title(strcat('Lane', num2str(lane_id)));

