%% ngsim model with smoothing patch of IDM model

function [pos, vel, error, acc]...
        = runIDM(pos_follower, ...
                       speed_follower, ....
                       pos_leader, ...
                       speed_leader,...
                       vehLen, ...
                       desire_headway, ...
                       deltaT,maxAcc,maxDec,...
                       jamGap,...
                       vf)
COMF_LEVEL=0.5;
                   
d_star = jamGap+max(0, speed_follower*desire_headway...
    +speed_follower*(speed_follower-speed_leader)/(2*sqrt(maxAcc*maxDec*COMF_LEVEL)));

acc = maxAcc*...
    (1-(speed_follower/vf)^4-d_star/(pos_leader-pos_follower-vehLen));

acc = max(-maxDec, acc);

vel = speed_follower+acc*deltaT;

pos = pos_follower+speed_follower * deltaT + 0.5*acc* deltaT * deltaT;

error=0;
